name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting an improvement! Please describe what you'd like to see.

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem does this solve? What's the use case?
      placeholder: I'm trying to do X but currently have to...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this to work?
      placeholder: It would be great if `hckg` could...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any other approaches you've considered?

  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - CLI
        - Synthetic Generation
        - Auto KG Construction
        - Graph Engine
        - Export / Import
        - Analysis / Queries
        - Documentation
        - Other
