#!/usr/bin/env bash
# kg-eod.sh — End-of-day: final sync + open PR to main.
#
# Called at 5 pm by LaunchAgent (macOS) or systemd timer (Linux).
# Also callable manually.
#
# Usage:
#   bash kg-eod.sh [--dry-run]
#
# Environment:
#   HCKG_DATA_DIR   — path to hc-cdaio-kg clone  (default: ~/hc-cdaio-kg)
#   HCKG_GRAPH_SRC  — path to live graph.json     (default: ~/hc-enterprise-kg/graph.json)
#   HCKG_BRANCH     — branch to PR from           (default: auto-detected)

set -euo pipefail
IFS=$'\n\t'

# ── Config ───────────────────────────────────────────────────────────────────
DATA_DIR="${HCKG_DATA_DIR:-${HOME}/hc-cdaio-kg}"
GRAPH_SRC="${HCKG_GRAPH_SRC:-${HOME}/hc-enterprise-kg/graph.json}"
SCRIPTS_DIR="$(cd "$(dirname "$0")" && pwd)"
LOG_FILE="${DATA_DIR}/.kg-eod.log"
DRY_RUN=0
REPO_OWNER="thehipsterciso"
REPO_NAME="hc-cdaio-kg"
REPO_FULL="${REPO_OWNER}/${REPO_NAME}"

# ── Args ─────────────────────────────────────────────────────────────────────
while [[ $# -gt 0 ]]; do
  case "$1" in
    --dry-run) DRY_RUN=1; shift ;;
    *) echo "Unknown argument: $1" >&2; exit 1 ;;
  esac
done

# ── Logging ──────────────────────────────────────────────────────────────────
_ts() { date '+%Y-%m-%d %H:%M:%S'; }
log() { printf '[%s] %s\n' "$(_ts)" "$*" | tee -a "${LOG_FILE}" >&2; }

if [[ -f "${LOG_FILE}" ]] && [[ $(wc -c < "${LOG_FILE}") -gt 1048576 ]]; then
  mv "${LOG_FILE}" "${LOG_FILE}.1"
fi

log "kg-eod: start (dry_run=${DRY_RUN})"

# ── Sanity checks ────────────────────────────────────────────────────────────
[[ -d "${DATA_DIR}/.git" ]] || { log "ERROR: ${DATA_DIR} is not a git repo"; exit 1; }
command -v gh &>/dev/null   || { log "ERROR: gh CLI not found"; exit 1; }
gh auth status &>/dev/null  || { log "ERROR: gh not authenticated"; exit 1; }

# ── 1. Final sync ────────────────────────────────────────────────────────────
log "Running final sync"
if [[ $DRY_RUN -eq 0 ]]; then
  bash "${SCRIPTS_DIR}/kg-sync.sh" --message "eod: end-of-day sync at $(_ts)" \
    2>>"${LOG_FILE}" || log "WARN: sync had warnings (continuing)"
fi

# ── 2. Detect branch ─────────────────────────────────────────────────────────
BRANCH="${HCKG_BRANCH:-}"
if [[ -z "${BRANCH}" ]]; then
  BRANCH="$(git -C "${DATA_DIR}" rev-parse --abbrev-ref HEAD 2>/dev/null || echo "")"
fi
[[ -z "${BRANCH}" || "${BRANCH}" == "main" ]] \
  && { log "SKIP: already on main or no branch detected — nothing to PR"; exit 0; }

log "Branch: ${BRANCH}"

# ── 3. Check if branch has commits ahead of main ─────────────────────────────
git -C "${DATA_DIR}" fetch origin main --quiet 2>>"${LOG_FILE}" || true
AHEAD=$(git -C "${DATA_DIR}" rev-list --count "origin/main..${BRANCH}" 2>/dev/null || echo "0")
if [[ "${AHEAD}" == "0" ]]; then
  log "Branch ${BRANCH} has no commits ahead of main — nothing to PR"
  exit 0
fi
log "Branch is ${AHEAD} commit(s) ahead of main"

# ── 4. Check for existing open PR ────────────────────────────────────────────
EXISTING_PR="$(gh pr list \
  --repo "${REPO_FULL}" \
  --head "${BRANCH}" \
  --base main \
  --state open \
  --json number \
  --jq '.[0].number' 2>/dev/null || echo "")"

if [[ -n "${EXISTING_PR}" ]]; then
  log "Open PR #${EXISTING_PR} already exists for ${BRANCH} — skipping creation"
  log "  https://github.com/${REPO_FULL}/pull/${EXISTING_PR}"
  exit 0
fi

# ── 5. Create PR ─────────────────────────────────────────────────────────────
TODAY="$(date '+%Y-%m-%d')"
MEMBER="$(echo "${BRANCH}" | cut -d'/' -f1)"
PR_TITLE="[${TODAY}] EOD sync — ${MEMBER}"
PR_BODY="$(cat <<EOF
## End-of-day knowledge graph update

- **Author**: ${MEMBER}
- **Date**: ${TODAY}
- **Branch**: \`${BRANCH}\`
- **Commits ahead of main**: ${AHEAD}

Auto-generated by \`kg-eod.sh\`. Review the per-type JSON diffs and merge when ready.

### Merge checklist
- [ ] Entity diffs look correct
- [ ] No unintended deletions
- [ ] Relationships reference valid entity IDs
EOF
)"

if [[ $DRY_RUN -eq 1 ]]; then
  log "DRY RUN — would create PR:"
  log "  Title: ${PR_TITLE}"
  log "  Base:  main  ←  Head: ${BRANCH}"
  exit 0
fi

PR_URL="$(gh pr create \
  --repo "${REPO_FULL}" \
  --title "${PR_TITLE}" \
  --body "${PR_BODY}" \
  --base main \
  --head "${BRANCH}" \
  2>>"${LOG_FILE}")"

log "PR created: ${PR_URL}"

# ── 6. Optional macOS notification ──────────────────────────────────────────
if command -v osascript &>/dev/null; then
  osascript -e "display notification \"EOD PR opened: ${PR_TITLE}\" with title \"hc-cdaio-kg\"" \
    2>/dev/null || true
fi

log "kg-eod: done"
